PRO-263 paginate list of offices in selectofficemodal
ProjectProtocol/project-protocol-web pull request #100
Opened 2024-02-07 19:58 UTC by yuuks

Currently WIP.

2024-02-07 20:02 UTC, yuuks commented
Overall, looking for feedback on patterns and structure, which I'm still getting a feel for.

In addition there's an issue where when you update the search text, it will show the previous result's search for a sec. (for example: type 'a', wait for results to display, then delete and type 'l', and you'll see the previous results displayed until the results are fetched). So need to figure out a way to clear results when search text changes.

2024-02-09 00:29 UTC, tasandberg requested changes
Code looks good and list loads great, tested in preview and local. Only nit was to remove the old SearchData type declaration in `src/api/search.ts.`

2024-02-09 00:29 UTC, tasandberg commented on src/api/search.ts
> +export type SearchData<T> = {
I think this SearchData should be deleted in favor of the new `SearchData.ts` definition in `src/types`

2024-02-09 01:31 UTC, tasandberg approved these changes

2024-02-09 21:12 UTC, tasandberg commented
@yuuks In the future feel free to merge branches once approved. I'm taking the liberties since I'm pairing with Eddie and we need the new SearchData type :D

2024-02-09 21:12 UTC, merged